#!/bin/bash
Directory_Name="assignment_dir"
Path="/home/Shell_scripts/asiignment_dir"

if [ -d"$Path" ]; then
echo "Directory with a Name $Directory_Name exists in the Location"
else
echo "No such Directory"

fi
